version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/docker"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Django"
        update-types: ["version-update:semver-major"] # keep 5.2 LTS
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

