# Generated by Django 5.2.16 on 2026-07-07 15:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='File name *with* extension.', max_length=100, unique=True)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
    ]
