# ---------------------
# /etc/nginx/nginx.conf
# ---------------------

worker_processes auto;
pid /var/run/nginx.pid;

# Log errors to syslog-ng server; unfortunately, error_log doesn't use iso8601
error_log syslog:server=syslog,tag=NGINX,nohostname info;

# Each worker handles 1024 connections at most. See `ulimit -n`.
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Send access log in custom format to syslog-ng server.
    log_format access_log_format '[$time_iso8601] $scheme "$request" $status '
        '$body_bytes_sent "$http_user_agent"';
    access_log syslog:server=syslog,tag=NGINX,severity=info,nohostname access_log_format;
    
    sendfile on;
    keepalive_timeout 65;
    include /etc/nginx/vol/conf.d/*.conf;
}
