def csp_nonce(request):
    """
    Passes the nonce generated by CSPMiddleware to each template's context.
    Usage: settings.py > TEMPLATES.
    """
    return {"csp_nonce": getattr(request, "csp_nonce", "")}
