# -------------------
# /etc/logrotate.conf
# -------------------

# Keep 14 versions of mysql, django, nginx logs each. A new version is created
# after min(one day, 100M size). Compress all non-current versions. Remove the
# shared volume data of mysql logs after rotation.
/var/log/portfolio/*.log {
    maxsize 100M
    compress
    missingok
    rotate 14
    daily
    sharedscripts
    postrotate
        : > /var/log/mysql/slow-query.log
        : > /var/log/mysql/general.log
        : > /var/log/mysql/error.log
        syslog-ng-ctl reload
    endscript
}
