# -----------------------------
# /etc/syslog-ng/syslog-ng.conf
# -----------------------------

@version: 4.6

# Django, NGINX, Gunicorn send logs to UDP:514
source s_network { udp( ip("0.0.0.0") port(514) ); };

# MySQL shares logs via volume
source s_mysql_general { file("/var/log/mysql/general.log"); };
source s_mysql_error { file("/var/log/mysql/error.log"); };
source s_mysql_slow { file("/var/log/mysql/slow-query.log"); };

# Filter raw log messages
filter f_nginx { program("NGINX"); };
filter f_django { program("DJANGO"); };
filter f_mysql_general { message("Query"); }; # store logs containing "Query"
filter f_gunicorn_error { program("gunicorn.GUNICORN.error") };

# Format logs (remove unnecessary information)
template t_custom {
    template("${MESSAGE}\n");
};
template t_mysql {
    template("${ISODATE} ${MESSAGE}\n");
};

# Strip client IP address from NGINX error log
rewrite r_nginx_strip_ip {
    subst("client:? ?(.*?)[\\s,]", " STRIPPED-CLIENT-IP ", value("MESSAGE"), flags("global"));
};

# Where to store filtered logs
destination d_nginx {
    file(
        "/var/log/portfolio/nginx.log"
        template(t_custom)
        create-dirs(yes)
    );
};
destination d_django {
    file(
        "/var/log/portfolio/django.log"
        template(t_custom)
        create-dirs(yes)
    );
};
destination d_gunicorn_error {
    file(
        "/var/log/portfolio/gunicorn-error.log",
        template(t_custom),
        create-dirs(yes)
    );
};
destination d_mysql_general {
    file(
        "/var/log/portfolio/mysql-general.log"
        template(t_mysql)
        create-dirs(yes)
    );
};
destination d_mysql_slow {
    file(
        "/var/log/portfolio/mysql-slow-query.log"
        template(t_mysql)
        create-dirs(yes)
    );
};
destination d_mysql_error {
    file(
        "/var/log/portfolio/mysql-error.log"
        template(t_mysql)
        create-dirs(yes)
    );
};

# Put everything together
log {
    source(s_mysql_general);
    filter(f_mysql_general);
    destination(d_mysql_general);
};
log {
    source(s_mysql_slow);
    destination(d_mysql_slow);
};
log {
    source(s_mysql_error);
    destination(d_mysql_error);
};
log {
    source(s_network);
    filter(f_nginx);
    rewrite(r_nginx_strip_ip);
    destination(d_nginx);
};
log {
    source(s_network);
    filter(f_django);
    destination(d_django);
};
log {
    source(s_network);
    filter(f_gunicorn_error);
    destination(d_gunicorn_error);
};
