# Generated by Django 5.2.16 on 2026-07-07 15:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Image name *without* extension.', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, help_text=" Currently, the maximum upload size is 10MB. Change\n        'client_max_body_size <size>;' in nginx configuration if necessary. ", storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to='blog_images/')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('teaser', models.CharField(max_length=500)),
                ('content', models.TextField(null=True)),
                ('datetime_published', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_modified', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(blank=True)),
                ('is_draft', models.BooleanField(blank=True, default=False)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tags')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-datetime_published'],
            },
        ),
    ]
